### PR TITLE
update resin-settings-storage and add the browser tests

### PR DESCRIPTION
**Pull request by emirotin**

### CODE REVIEW

**Comment by jviotti** [comment]
Looks great! Do you need me to merge here as well? Looks like there are tons of modules that weren't moved to `resin-io-modules` at all :/

**Comment by emirotin** [comment]
Yeah, I can't merge on resin-io repos that I'm not added to directly.
Please merge and publish _or_ move and give me the permissions (I could build and publish myself given the needed permissions and npm creds). I suspect I'm going to tap half a dozen more modules :)

**Comment by jviotti** [comment]
I see. I've added you to all repositories, so you can merge and publish yourself and don't have to depend on me. Let me know if you encounter any repo where you still don't have permissions in (I've added you to the cli/sdk team, which _should_ be including all repos).

**Comment by emirotin** [comment]
Thanks! I can merge here now.
Would you mind sharing the required `npm` creds in passpack so that I can publish as well?

**Comment by jviotti** [comment]
I sadly don't seem to have enough permissions to share the credentials
(just view them), so I guess reaching out to Apostolis/Aggelos would be
the way to go. Alternative, I can publish now so you don't get blocked
by it.

Let me know!

On Fri, Sep 09, 2016 at 02:08:32PM -0700, Eugene Mirotin wrote:

> Thanks! I can merge here now.
> Would you mind sharing the required `npm` creds in passpack so that I can publish as well?
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/resin-token/pull/25#issuecomment-246040411

## 

Juan Cruz Viotti
Software Engineer

**Comment by emirotin** [comment]
OK please publish now then.

**Comment by emirotin** [comment]
All good @jviotti I happened to have access, published v2.4.3 to npm.
Hope all looks good

**Pull request merged**
